package gui;

import javax.swing.JOptionPane;
import modelo.Curso;
import dao.CursoDAO;

/**
 *
 * @author CELSO
 */
public class JanelaCurso extends javax.swing.JFrame {

    private CursoDAO cursoDAO = new CursoDAO();
    private Curso cursoSelecionado = null;

    /**
     * Creates new form JanelaCurso
     */
    public JanelaCurso() {
        initComponents();
    }
    
    cuzniho
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeCurso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCargaHoraria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLimiteAlunos = new javax.swing.JTextField();
        chkAtivo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        bntNovo = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        bntSalvar = new javax.swing.JButton();
        bntInativar = new javax.swing.JButton();
        bntReativar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome curso");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        txtNomeCurso.setText("nome curso");
        txtNomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCursoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel2.setText("Carga horaria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtCargaHoraria.setText("carga horaria");
        getContentPane().add(txtCargaHoraria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel3.setText("Limite Alunos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        txtLimiteAlunos.setText("limite alunos");
        txtLimiteAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimiteAlunosActionPerformed(evt);
            }
        });
        getContentPane().add(txtLimiteAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        chkAtivo.setText("Ativo");
        getContentPane().add(chkAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Curso", "Carga Horaria", "limite Alunos", "Ativo"
            }
        ));
        jScrollPane1.setViewportView(tblCursos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, 40));

        bntNovo.setText("Novo");
        bntNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNovoActionPerformed(evt);
            }
        });
        getContentPane().add(bntNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        bntExcluir.setText("Excluir");
        getContentPane().add(bntExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        bntEditar.setText("Editar");
        getContentPane().add(bntEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(bntSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        bntInativar.setText("Inativar");
        getContentPane().add(bntInativar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        bntReativar.setText("Reativar");
        getContentPane().add(bntReativar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCursoActionPerformed

    private void txtLimiteAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimiteAlunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLimiteAlunosActionPerformed

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        // TODO add your handling code here:
        // Validação
        String nome = txtNomeCurso.getText().trim();
        String cargaStr = txtCargaHoraria.getText().trim();
        String limiteStr = txtLimiteAlunos.getText().trim();

        if (nome.length() < 3) {
            JOptionPane.showMessageDialog(this, "Nome deve ter pelo menos 3 caracteres.");
            return;
        }
        int carga;
        try {
            carga = Integer.parseInt(cargaStr);
            if (carga < 20) {
                JOptionPane.showMessageDialog(this, "Carga horária mínima é 20.");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Carga horária inválida.");
            return;
        }
        int limite;
        try {
            limite = Integer.parseInt(limiteStr);
            if (limite < 1) {
                JOptionPane.showMessageDialog(this, "Limite de alunos deve ser pelo menos 1.");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Limite de alunos inválido.");
            return;
        }

        boolean ativo = jCheckBox1.isSelected();

        CursoDAO dao = new CursoDAO();
        Curso c = new Curso();
        c.setNome(nome);
        c.setCargaHoraria(carga);
        c.setLimiteAlunos(limite);
        c.setAtivo(ativo);

        // Verifica se está editando ou criando novo
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            // Novo
            dao.adiciona(c);
            JOptionPane.showMessageDialog(this, "Curso cadastrado!");
        } else {
            // Editar
            int id = (int) jTable1.getValueAt(row, 0);
            c.setId(id);
            dao.altera(c);
            JOptionPane.showMessageDialog(this, "Curso alterado!");
        }
        atualizarTabela();
        limparCampos();

    }//GEN-LAST:event_bntSalvarActionPerformed

    private void bntNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNovoActionPerformed
        // TODO add your handling code here:
        txtNomeCurso.setText("");
        txtCargaHoraria.setText("");
        txtLimiteAlunos.setText("");
        chkAtivo.setSelected(true);
        cursoSelecionado = null;
        tblCursos.clearSelection();
    }//GEN-LAST:event_bntNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntInativar;
    private javax.swing.JButton bntNovo;
    private javax.swing.JButton bntReativar;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField txtCargaHoraria;
    private javax.swing.JTextField txtLimiteAlunos;
    private javax.swing.JTextField txtNomeCurso;
    // End of variables declaration//GEN-END:variables
}
